version: '3.2'

networks:
  lan:

services:
  web:
    image: wyveo/nginx-php-fpm:php74
    container_name: web
    restart: always
    volumes:
      - ./magento:/var/www/html:cache
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "8022:22"
  # mysql:
  #   image: mysql:5.7
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: mysql
  #   tty: true
  #   ports:
  #     - "4306:3306"
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #     - ./mysql/logs:/var/log/mysql
  #   networks:
  #     - lan
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   restart: always
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #     - PMA_USER=homestead
  #     - PMA_PASSWORD=secret
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - lan